name: data_dex
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^7.8.4
  bottom_bar_page_transition: ^2.0.0
  cloud_firestore: ^4.15.6
  dartz: ^0.10.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  geolocator: ^8.2.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  rxdart: ^0.27.7
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
