// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkXgljxeHEw5TPr6XedQKQYfP4GoZaKGA',
    appId: '1:194005231179:android:4cce7c64fc42a8c9de8fce',
    messagingSenderId: '194005231179',
    projectId: 'data-dex-a1841',
    storageBucket: 'data-dex-a1841.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiJZpnesKAcdbIdEtnRmN_qE9b14J2XfU',
    appId: '1:194005231179:ios:e56b3a69c751aebcde8fce',
    messagingSenderId: '194005231179',
    projectId: 'data-dex-a1841',
    storageBucket: 'data-dex-a1841.appspot.com',
    androidClientId: '194005231179-a9dl497as8f7dgd0g63f5g7t7hodci8r.apps.googleusercontent.com',
    iosClientId: '194005231179-ih4q77nfb8b7o38493bjjfs56uksuv0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataDex',
  );
}
